version: '3.8'

# Docker Master - Low RAM Configuration
# Optimized for systems with 4GB RAM or less
# Total RAM usage: ~448MB (6 containers)
# PHP 8.4: Laravel (128MB) + PHP 7.4: Laravel (128MB) + WordPress (128MB)
# PostgreSQL (128MB) + Redis (32MB) + Mailhog (32MB)
# Note: All services use PostgreSQL (no MySQL to save RAM)

services:
  # PostgreSQL - optimized for low memory
  postgres:
    image: postgres:15
    container_name: postgres_low_ram
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=docker_master
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_SHARED_BUFFERS=16MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=64MB
      - POSTGRES_WORK_MEM=2MB
      - POSTGRES_MAINTENANCE_WORK_MEM=8MB
      - POSTGRES_MAX_CONNECTIONS=25
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - low-ram-network

  # Redis - minimal configuration
  redis:
    image: redis:7-alpine
    container_name: redis_low_ram
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --maxmemory 16mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
    networks:
      - low-ram-network

  # Laravel PHP 8.4 - single optimized container
  laravel-php84:
    build:
      context: ./docker/php84
      dockerfile: Dockerfile
    container_name: laravel_php84_low_ram
    restart: unless-stopped
    ports:
      - "8010:80"
      - "9084:9003"  # Xdebug port
    volumes:
      - ./projects/laravel-php84-psql:/var/www/html
      - ./logs/apache/laravel-php84:/var/log/apache2
      - ./data/uploads/laravel-php84:/app/uploads
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
      - PHP_VERSION=8.4
      - PHP_MEMORY_LIMIT=96M
      - PHP_OPCACHE_MEMORY_CONSUMPTION=32
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=1000
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres_low_ram
      - DB_PORT=5432
      - DB_DATABASE=laravel_php84_psql
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_pass
      - REDIS_HOST=redis_low_ram
      - REDIS_PORT=6379
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 96M
    networks:
      - low-ram-network
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Laravel PHP 7.4 - optimized container
  laravel-php74:
    build:
      context: ./docker/php74
      dockerfile: Dockerfile
    container_name: laravel_php74_low_ram
    restart: unless-stopped
    ports:
      - "8020:80"
      - "9074:9003"  # Xdebug port
    volumes:
      - ./projects/laravel-php74-psql:/var/www/html
      - ./logs/apache/laravel-php74:/var/log/apache2
      - ./data/uploads/laravel-php74:/app/uploads
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
      - PHP_VERSION=7.4
      - PHP_MEMORY_LIMIT=96M
      - PHP_OPCACHE_MEMORY_CONSUMPTION=32
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=1000
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres_low_ram
      - DB_PORT=5432
      - DB_DATABASE=laravel_php74_psql
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_pass
      - REDIS_HOST=redis_low_ram
      - REDIS_PORT=6379
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 96M
    networks:
      - low-ram-network
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # WordPress PHP 7.4 - optimized container (using PostgreSQL)
  wordpress-php74:
    build:
      context: ./docker/php74
      dockerfile: Dockerfile
    container_name: wordpress_php74_low_ram
    restart: unless-stopped
    ports:
      - "8030:80"
      - "9075:9003"  # Xdebug port (different from Laravel 7.4)
    volumes:
      - ./projects/wordpress-php74-mysql:/var/www/html
      - ./logs/apache/wordpress-php74:/var/log/apache2
      - ./data/uploads/wordpress-php74:/app/uploads
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
      - PHP_VERSION=7.4
      - PHP_MEMORY_LIMIT=96M
      - PHP_OPCACHE_MEMORY_CONSUMPTION=32
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=1000
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres_low_ram
      - DB_PORT=5432
      - DB_DATABASE=wordpress_php74
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_pass
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 96M
    networks:
      - low-ram-network
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3



  # Mailhog - lightweight email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_low_ram
    restart: unless-stopped
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
    networks:
      - low-ram-network

# Network
networks:
  low-ram-network:
    driver: bridge
    name: docker_master_low_ram

# Volumes for data persistence
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
