version: '3.8'

# Docker Master - Low RAM Configuration
# Optimized for systems with 4GB RAM or less
# Total RAM usage: ~448MB (6 containers)
# PHP 8.4: Laravel (128MB) + PHP 7.4: Laravel (128MB) + WordPress (128MB)
# PostgreSQL (128MB) + Redis (32MB) + Mailhog (32MB)
# Note: All services use PostgreSQL (no MySQL to save RAM)

services:
  # PostgreSQL - optimized for low memory
  postgres:
    image: postgres:15
    container_name: postgres_low_ram
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=docker_master
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_SHARED_BUFFERS=16MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=64MB
      - POSTGRES_WORK_MEM=2MB
      - POSTGRES_MAINTENANCE_WORK_MEM=8MB
      - POSTGRES_MAX_CONNECTIONS=25
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - low-ram-network

  # Redis - minimal configuration
  redis:
    image: redis:7-alpine
    container_name: redis_low_ram
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --maxmemory 16mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
    networks:
      - low-ram-network

  # Laravel PHP 8.4 - single optimized container
  laravel-php84:
    build:
      context: ./docker/php84
      dockerfile: Dockerfile
    container_name: laravel_php84_low_ram
    restart: unless-stopped
    ports:
      - "8010:80"
      - "9084:9003"  # Xdebug port
    volumes:
      - ./projects/laravel-php84-psql:/var/www/html
      - ./logs/apache/laravel-php84:/var/log/apache2
      - ./data/uploads/laravel-php84:/app/uploads
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
      - PHP_VERSION=8.4
      - PHP_MEMORY_LIMIT=96M
      - PHP_OPCACHE_MEMORY_CONSUMPTION=32
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=1000
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres_low_ram
      - DB_PORT=5432
      - DB_DATABASE=laravel_php84_psql
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_pass
      - REDIS_HOST=redis_low_ram
      - REDIS_PORT=6379
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 96M
    networks:
      - low-ram-network
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Laravel PHP 7.4 - optimized container
  laravel-php74:
    build:
      context: ./docker/php74
      dockerfile: Dockerfile
    container_name: laravel_php74_low_ram
    restart: unless-stopped
    ports:
      - "8020:80"
      - "9074:9003"  # Xdebug port
    volumes:
      - ./projects/laravel-php74-psql:/var/www/html
      - ./logs/apache/laravel-php74:/var/log/apache2
      - ./data/uploads/laravel-php74:/app/uploads
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
      - PHP_VERSION=7.4
      - PHP_MEMORY_LIMIT=96M
      - PHP_OPCACHE_MEMORY_CONSUMPTION=32
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=1000
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres_low_ram
      - DB_PORT=5432
      - DB_DATABASE=laravel_php74_psql
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_pass
      - REDIS_HOST=redis_low_ram
      - REDIS_PORT=6379
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 96M
    networks:
      - low-ram-network
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # WordPress PHP 7.4 - optimized container (using PostgreSQL)
  wordpress-php74:
    build:
      context: ./docker/php74
      dockerfile: Dockerfile
    container_name: wordpress_php74_low_ram
    restart: unless-stopped
    ports:
      - "8030:80"
      - "9075:9003"  # Xdebug port (different from Laravel 7.4)
    volumes:
      - ./projects/wordpress-php74-mysql:/var/www/html
      - ./logs/apache/wordpress-php74:/var/log/apache2
      - ./data/uploads/wordpress-php74:/app/uploads
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
      - PHP_VERSION=7.4
      - PHP_MEMORY_LIMIT=96M
      - PHP_OPCACHE_MEMORY_CONSUMPTION=32
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=1000
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres_low_ram
      - DB_PORT=5432
      - DB_DATABASE=wordpress_php74
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_pass
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 96M
    networks:
      - low-ram-network
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3



  # Mailhog - lightweight email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_low_ram
    restart: unless-stopped
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
    networks:
      - low-ram-network

  # Nginx Proxy - Domain routing for platforms
  nginx_proxy:
    image: nginx:alpine
    container_name: nginx_proxy_low_ram
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
    networks:
      - low-ram-network
    depends_on:
      - mysql_low_ram
      - postgres
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # MySQL 8.0 - RAM optimized for dual database support
  mysql_low_ram:
    image: mysql:8.0
    container_name: mysql_low_ram
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: main_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pass
    command: >
      --default-authentication-plugin=mysql_native_password
      --innodb-buffer-pool-size=128M
      --innodb-redo-log-capacity=64M
      --key-buffer-size=32M
      --table-open-cache=256
      --sort-buffer-size=2M
      --read-buffer-size=1M
      --read-rnd-buffer-size=2M
      --thread-cache-size=32
      --tmp-table-size=32M
      --max-heap-table-size=32M
      --skip-name-resolve
      --max-connections=100
      --wait-timeout=28800
      --interactive-timeout=28800
      --skip-host-cache
    volumes:
      - mysql_data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    networks:
      - low-ram-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mysql_user", "-pmysql_pass"]
      interval: 30s
      timeout: 10s
      retries: 3

# Network
networks:
  low-ram-network:
    driver: bridge
    name: docker_master_low_ram

# Volumes for data persistence
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  mysql_data:
    driver: local
