# Docker Master Platform - Examples
# 3 Example platforms demonstrating different PHP versions and databases

version: '3.8'

include:
  # Shared services (MySQL, PostgreSQL, Redis, phpMyAdmin, etc.)
  - ./platforms/shared/docker-compose.shared.yml

  # Example platforms
  - ./platforms/laravel-php84-psql/docker-compose.laravel-php84-psql.yml
  - ./platforms/laravel-php74-psql/docker-compose.laravel-php74-psql.yml
  - ./platforms/wordpress-php74-mysql/docker-compose.wordpress-php74-mysql.yml

  # Optional: Auto-monitoring (uncomment to enable)
  # - ./docker-compose.monitoring.yml

# Global networks - removed to avoid conflicts with shared services
