#!/bin/bash

# Script tự động sync tất cả platforms vào main docker-compose.yml
# Usage: ./sync-platforms.sh

MAIN_COMPOSE="docker-compose.yml"
BACKUP_COMPOSE="docker-compose.yml.backup"

echo "🔄 Syncing platforms to main docker-compose.yml..."

# Backup file gốc
if [ -f "$MAIN_COMPOSE" ]; then
    cp "$MAIN_COMPOSE" "$BACKUP_COMPOSE"
    echo "📋 Backup created: $BACKUP_COMPOSE"
fi

# Tạo file docker-compose.yml mới
cat > "$MAIN_COMPOSE" << 'EOF'
# Docker Master Platform - Main Orchestration File
# Auto-generated by sync-platforms.sh

version: '3.8'

include:
EOF

# Tự động tìm và thêm tất cả platforms
echo "🔍 Discovering platforms..."

for dir in platforms/*/; do
    if [ -d "$dir" ]; then
        platform_name=$(basename "$dir")
        
        # Bỏ qua thư mục templates và base
        if [[ "$platform_name" != "templates" && "$platform_name" != "base" ]]; then
            # Tìm file docker-compose trong thư mục
            for compose_file in "$dir"docker-compose.*.yml; do
                if [ -f "$compose_file" ]; then
                    relative_path="./platforms/$platform_name/$(basename "$compose_file")"
                    echo "  - $relative_path" >> "$MAIN_COMPOSE"
                    echo "  ✅ Added: $platform_name"
                    break
                fi
            done
        fi
    fi
done

# Thêm networks section nếu cần
cat >> "$MAIN_COMPOSE" << 'EOF'

# Global networks
networks:
  app-network:
    name: docker_master_network
    external: true
EOF

echo ""
echo "✅ Sync completed!"
echo "📄 Main docker-compose.yml updated with all discovered platforms"
echo ""
echo "🚀 You can now run: ./platform-manager.sh start"
