version: '3.8'

# YAML Anchors - Định nghĩa templates
x-php-base: &php-base
  build:
    context: ../../docker/php84
    dockerfile: Dockerfile
  restart: unless-stopped
  environment: &php-env
    - WEB_DOCUMENT_ROOT=/app
    - PHP_VERSION=8.4
    - DB_HOST=mysql_server
    - DB_USERNAME=root
    - DB_PASSWORD=rootpassword123
    - REDIS_HOST=redis_server
  networks:
    - app-network
  volumes: &php-volumes
    - ./app:/app
    - ../../logs/apache:/var/log/apache2
    - ../../data/uploads:/app/uploads

x-laravel-base: &laravel-base
  <<: *php-base
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost/"]
    interval: 30s
    timeout: 10s
    retries: 3

services:
  # Laravel E-commerce
  laravel-ecommerce:
    <<: *laravel-base
    container_name: laravel_ecommerce_php84
    ports:
      - "8006:80"
    volumes:
      - ../../projects/laravel_ecommerce:/app/laravel_ecommerce
      - ../../logs/apache/laravel_ecommerce:/var/log/apache2
    environment:
      <<: *php-env
      - WEB_DOCUMENT_ROOT=/app/laravel_ecommerce

  # Laravel Shop (tái sử dụng cùng template)
  laravel-shop:
    <<: *laravel-base
    container_name: laravel_shop_php84
    ports:
      - "8007:80"
    volumes:
      - ../../projects/laravel_shop:/app/laravel_shop
      - ../../logs/apache/laravel_shop:/var/log/apache2
    environment:
      <<: *php-env
      - WEB_DOCUMENT_ROOT=/app/laravel_shop

networks:
  app-network:
    external: true
    name: docker_master_network
