<?php
/**
 * test-shop - Laravel PHP 7.4 + PostgreSQL + Redis
 * Auto-generated by Docker Master Platform
 */

echo "^<h1^>🛒 test-shop - Laravel PHP 7.4^</h1^>";
echo "^<div style='font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;'^>";

echo "^<h2^>📋 Platform Information^</h2^>";
echo "^<p^>^<strong^>Platform:^</strong^> test-shop^</p^>";
echo "^<p^>^<strong^>Type:^</strong^> Laravel PHP 7.4^</p^>";
echo "^<p^>^<strong^>PHP Version:^</strong^> " . phpversion() . "^</p^>";
echo "^<p^>^<strong^>Port:^</strong^> 8017^</p^>";

// Database test
echo "^<h2^>🗄️ PostgreSQL Connection^</h2^>";
$host = $_ENV['DB_HOST'] ?? 'postgres_low_ram';
$dbname = $_ENV['DB_DATABASE'] ?? 'test_shop_db';
$username = $_ENV['DB_USERNAME'] ?? 'postgres_user';
$password = $_ENV['DB_PASSWORD'] ?? 'postgres_pass';

try {
    $pdo = new PDO("pgsql:host=$host;port=5432;dbname=$dbname", $username, $password);
    echo "^<p^>✅ PostgreSQL connection successful!^</p^>";
} catch (Exception $e) {
    echo "^<p^>❌ Database failed: " . $e->getMessage() . "^</p^>";
}

// Redis test
echo "^<h2^>🔴 Redis Connection^</h2^>";
$redis_host = $_ENV['REDIS_HOST'] ?? 'redis_low_ram';
try {
    $redis = new Redis();
    $redis->connect($redis_host, 6379);
    echo "^<p^>✅ Redis connection successful!^</p^>";
} catch (Exception $e) {
    echo "^<p^>❌ Redis failed: " . $e->getMessage() . "^</p^>";
}

echo "^<p^>^<em^>🐳 test-shop ready for Laravel development!^</em^>^</p^>";
echo "^</div^>";
?>
