version: '3.8'

services:
  my-blog:
    build:
      context: ../../docker/php74
      dockerfile: Dockerfile
    container_name: asmofoodservice_php74
    restart: unless-stopped
    ports:
      - "8011:80"   # Web port for direct access
    expose:
      - "80"  # Internal port for Nginx proxy
    volumes:
      - ../../projects/asmo-foodservice/wordpress:/var/www/html
      - ../../logs/apache/asmo-foodservice:/var/log/apache2
      - ../../data/uploads/asmo-foodservice:/app/uploads
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
      - PHP_VERSION=74
      - PHP_MEMORY_LIMIT=96M
      - DB_CONNECTION=mysql
      - DB_HOST=mysql_low_ram
      - DB_PORT=3306
      - DB_DATABASE=foodservice
      - DB_USERNAME=mysql_user
      - DB_PASSWORD=mysql_pass
      - REDIS_HOST=redis_low_ram
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      - docker_master_low_ram
    external_links:
      - postgres_low_ram:postgres_low_ram
      - redis_low_ram:redis_low_ram
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  docker_master_low_ram:
    external: true
