version: '3.8'

services:
  my-shop:
    build:
      context: ../../docker/php84
      dockerfile: Dockerfile
    container_name: my-shop_php84
    restart: unless-stopped
    ports:
      - "8015:80"   # Web port for direct access
      - "9015:9003"   # Xdebug port
    expose:
      - "80"  # Internal port for Nginx proxy
    volumes:
      - ../../projects/my-shop:/var/www/html
      - ../../logs/apache/my-shop:/var/log/apache2
      - ../../data/uploads/my-shop:/app/uploads
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
      - PHP_VERSION=84
      - PHP_MEMORY_LIMIT=96M
      - DB_CONNECTION=mysql
      - DB_HOST=mysql_low_ram
      - DB_PORT=3306
      - DB_DATABASE=my_shop_db
      - DB_USERNAME=mysql_user
      - DB_PASSWORD=mysql_pass
      - REDIS_HOST=redis_low_ram
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      - docker_master_low_ram
    external_links:
      - postgres_low_ram:postgres_low_ram
      - redis_low_ram:redis_low_ram
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  docker_master_low_ram:
    external: true
