version: '3.8'

services:
  test-shop:
    build:
      context: ../../docker/php74
      dockerfile: Dockerfile
    container_name: test-shop_php74
    restart: unless-stopped
    ports:
      - "8017:80"
      - "9017:9003"  # Xdebug port
    volumes:
      - ../../projects/test-shop:/var/www/html
      - ../../logs/apache/test-shop:/var/log/apache2
      - ../../data/uploads/test-shop:/app/uploads
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
      - PHP_VERSION=74
      - PHP_MEMORY_LIMIT=96M
      - PHP_OPCACHE_MEMORY_CONSUMPTION=32
      - DB_HOST=postgres_low_ram
      - DB_PORT=5432
      - DB_DATABASE=test_shop_db
      - DB_USERNAME=postgres_user
      - DB_PASSWORD=postgres_pass
      - REDIS_HOST=redis_low_ram
      - REDIS_PORT=6379
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 96M
    networks:
      - docker_master_low_ram
    external_links:
      - postgres_low_ram:postgres_low_ram
      - redis_low_ram:redis_low_ram
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  docker_master_low_ram:
    external: true
